### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by gustavjoh** [tobbeost/umierrorcorrect#4]
Feature request - would be nice to have a argument to call out the version number of the package. Mainly to see if I was able to update the package or not

**Comment by tobbeost** [comment]
This is kind of fixed already, type `run_umierrorcorrect.py -h`, or help for any of the scripts, and the version number will appear in the header of the help section. Should be nice to write the version number out to stdout when the program is run. There is a file called __version__.py now that takes care of this.
