### ISSUE TITLE
Mutations as insertion is not quantified correctly

### ISSUE THREAD

**Issue by gustavjoh** [tobbeost/umierrorcorrect#5]
When looking at position with insertion the Coverage get a higher count than the other positions which leads to an error in quantification.

Contig | Position | Name | Reference | A | C | G | T | I | D | N | Coverage | Consensus group size | Max Non-ref Allele Count | Max Non-ref Allele Frequency
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chr4 | 54727426 | KIT_2_v4 | A | 3121 | 0 | 84 | 0 | 0 | 0 | 2 | 3207 | 3 | 84 | 0.026192703
chr4 | 54727427 | KIT_2_v4 | T | 210 | 3 | 19 | 2975 | 1735 | 0 | 0 | 4942 | 3 | 1735 | 0.35107244
chr4 | 54727428 | KIT_2_v4 | G | 0 | 0 | 3202 | 5 | 2 | 0 | 0 | 3209 | 3 | 5 | 0.001558118

**Comment by tobbeost** [comment]
This has been fixed in the new version v0.15 by not counting the insertions in the total coverage
