### ISSUE TITLE
Remove large files option

### ISSUE THREAD

**Issue by ozimand1as** [tobbeost/umierrorcorrect#7]
I think we've talked about it before, but I think it could be nice to have a flag so that large files (fastq, bam) are deleted. 

The bam file with the consensus reads is useful of course and should be kept.

**Comment by tobbeost** [comment]
A new option has been added to the scripts `run_umierrorcorrect.py`, `run_mapping.py` and `umi_error_correct.py`.

The option is the following:

>   -remove, --remove_large_files
                        Include this flag to emove the original Fastq and BAM
                        files (reads without error correction).

**Comment by tobbeost** [comment]
Updated in v0.15
